package MVCJuegoEnCurso.vista;

import MVCJuegoEnCurso.controlador.ControladorPartida;
import MVCJuegoEnCurso.modelo.interfaces.IModeloJugadoresLectura;
import MVCJuegoEnCurso.modelo.interfaces.IModeloTableroLectura;
import MVCJuegoEnCurso.observer.ObservadorJugadores;
import MVCJuegoEnCurso.observer.ObservadorTablero;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import MVCJuegoEnCurso.observer.ObservadorInicioPartida;
import MVCJuegoEnCurso.observer.ObservadorMensaje;
import MVCJuegoEnCurso.observer.ObservadorTurno;
import java.awt.Color;
import javax.swing.JOptionPane;
import objetosPresentables.JugadorPresentable;

/**
 * Vista que engloba una partida en curso. contiene a los jugadores y al
 * tablero.
 *
 * @author victoria
 */
public class FrmPartida extends JFrame implements ObservadorInicioPartida, ObservadorTurno, ObservadorMensaje {

    private PnlTablero tablero;
    private PnlJugadores jugadores;
    private JugadorPresentable sesion;
    private ControladorPartida controlador;
    private final Color COLOR_FONDO = new Color(224, 233, 255);

    public FrmPartida(IModeloJugadoresLectura modeloJugadores, IModeloTableroLectura modeloTablero, ControladorPartida controlador) {
        initComponents();

        tablero = new PnlTablero(modeloTablero, controlador);
        jugadores = new PnlJugadores(modeloJugadores, controlador);

        jugadores.agregarObservadorturno(this);
        sesion = modeloJugadores.getJugadorSesion();

        add(tablero, BorderLayout.CENTER);
        add(jugadores, BorderLayout.WEST);
        this.setBackground(COLOR_FONDO);
        this.pnlFooter.setBackground(COLOR_FONDO);
        this.setLocationRelativeTo(null);
        this.controlador = controlador;
        setSize(1050, 740);

        // Deshabilitar tablero si no es el turno del jugador sesion
        actualizarEstadoTablero();
    }

    private void actualizarEstadoTablero() {
        JugadorPresentable jugadorEnTurno = jugadores.getJugadorEnTurno();
        boolean estaEnTurno = jugadorEnTurno != null
                && jugadorEnTurno.getNombre().equals(sesion.getNombre());
        tablero.setInteraccionHabilitada(estaEnTurno);

        //jesus en moto
        if (estaEnTurno) {
            System.out.println("[" + sesion.getNombre() + "] Es tu turno");
        } else {
            System.out.println("[" + sesion.getNombre() + "] Esperando turno de: "
                    + (jugadorEnTurno != null ? jugadorEnTurno.getNombre() : "???"));
        }
    }

    @Override
    public void mostrarMensaje() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres abandonar la partida?",
                "Confirmación",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        eleccionAbandonar(opcion);
    }

    public void eleccionAbandonar(int opcion) {
        if (opcion == JOptionPane.OK_OPTION) {
            System.out.println("[FRM Partida]: Abandonaste la partida");
            controlador.abandonarPartida();
        } else if (opcion == JOptionPane.CANCEL_OPTION) {
        }
    }

    public ObservadorTablero getObservadorTablero() {
        return (ObservadorTablero) tablero;
    }

    public ObservadorJugadores getObservadorJugadores() {
        return (ObservadorJugadores) jugadores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFooter = new javax.swing.JPanel();
        btnFinalizarPartida = new javax.swing.JButton();
        btnAbandonarPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        pnlFooter.setPreferredSize(new java.awt.Dimension(300, 100));

        btnFinalizarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/finalizarPartida.png"))); // NOI18N
        btnFinalizarPartida.setBorder(null);
        btnFinalizarPartida.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/finalizarPartidaHover.png"))); // NOI18N
        btnFinalizarPartida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/finalizarPartidaHover.png"))); // NOI18N
        btnFinalizarPartida.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/finalizarPartidaHover.png"))); // NOI18N

        btnAbandonarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/abandonarPartida.png"))); // NOI18N
        btnAbandonarPartida.setBorder(null);
        btnAbandonarPartida.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/abandonarPartidaHover.png"))); // NOI18N
        btnAbandonarPartida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/abandonarPartidaHover.png"))); // NOI18N
        btnAbandonarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnFinalizarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAbandonarPartida)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbandonarPartida))
                .addGap(69, 69, 69))
        );

        getContentPane().add(pnlFooter, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbandonarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaActionPerformed

        controlador.mostrarMensaje();

    }//GEN-LAST:event_btnAbandonarPartidaActionPerformed
    // recibe notificacion del modelo de que el juego ya inicia
    @Override
    public void mostrarJuego() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonarPartida;
    private javax.swing.JButton btnFinalizarPartida;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        actualizarEstadoTablero();
    }
}
