package MVCJuegoEnCurso.vista;


import MVCJuegoEnCurso.controlador.ControladorPartida;
import MVCJuegoEnCurso.modelo.interfaces.IModeloJugadoresLectura;
import MVCJuegoEnCurso.modelo.interfaces.IModeloTableroLectura;
import MVCJuegoEnCurso.observer.ObservadorJugadores;
import MVCJuegoEnCurso.observer.ObservadorTablero;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import MVCJuegoEnCurso.observer.ObservadorInicioPartida;

/**
 *
 * @author victoria
 */
public class FrmPartida extends JFrame implements ObservadorInicioPartida {

    private PnlTablero tablero;
    private PnlJugadores jugadores;

    public FrmPartida(IModeloJugadoresLectura modeloJugadores, IModeloTableroLectura modeloTablero, ControladorPartida controlador) {
        initComponents();

        tablero = new PnlTablero(modeloTablero, controlador);
        jugadores = new PnlJugadores(modeloJugadores, controlador);

        add(tablero, BorderLayout.CENTER);
        add(jugadores, BorderLayout.WEST);
        setSize(1050, 640);
    }

    public ObservadorTablero getObservadorTablero() {
        return (ObservadorTablero) tablero;
    }

    public ObservadorJugadores getObservadorJugadores(){
        return (ObservadorJugadores) jugadores;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void mostrarJuego() {
       this.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
