package MVCJuegoEnCurso.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import objetosPresentables.JugadorPresentable;

/**
 *
 * @author victoria
 */
public class PnlJugador extends JPanel {

    private JugadorPresentable jugador;
    private PnlJugadores panelJugadores;

    public PnlJugador(JugadorPresentable jugador) {
        initComponents();
        this.jugador = jugador;
        cargarDatos();
        //enTurno();

    }

    public void cargarDatos() {
        Image avatar = jugador.getAvatar();
        this.lblAvatar.setIcon(new ImageIcon(avatar));
        this.lblNombre.setText(jugador.getNombre());
        this.lblNombre.setForeground(jugador.getColor());
        this.lblPuntos.setText(String.valueOf(jugador.getScore()));
        //enTurno();

    }

    private void enTurno() {
        if (jugador.isTurno()) {
            this.lblNombre.setForeground(jugador.getColor());
            this.lblPuntos.setForeground(jugador.getColor());
        } else {
            this.lblNombre.setForeground(Color.GRAY);
            this.lblPuntos.setForeground(Color.GRAY);
        }
    }

    public JugadorPresentable getJugador() {
        return jugador;
    }

    public void setJugador(JugadorPresentable jugador) {
        this.jugador = jugador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();

        lblNombre.setForeground(new java.awt.Color(204, 204, 255));
        lblNombre.setText("NombreJugador");

        lblPuntos.setText("00");

        jLabel3.setText("puntos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblAvatar)
                .addGap(109, 109, 109)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPuntos)
                        .addGap(14, 14, 14)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblAvatar))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntos;
    // End of variables declaration//GEN-END:variables
}
