package MVCJuegoEnCurso.vista;

import MVCJuegoEnCurso.observer.ObservadorAbandono;
import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.GrayFilter;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import objetosPresentables.JugadorPresentable;

/**
 * Panel que representa gráficamente a un jugador de la partida.
 *
 * @author victoria
 */
public class PnlJugador extends JPanel{

    private JugadorPresentable jugador;
    private PnlJugadores panelJugadores;

    public PnlJugador(JugadorPresentable jugador) {
        initComponents();
        this.jugador = jugador;
        this.setOpaque(false);
        cargarDatos();
        enTurno();

    }

    public void cargarDatos() {
        Image avatar = jugador.getAvatar();
        this.lblAvatar.setIcon(new ImageIcon(avatar));
        this.lblNombre.setText(jugador.getNombre());
        this.lblNombre.setForeground(jugador.getColor());
        this.lblPuntos.setText(String.valueOf(jugador.getScore()));
        this.lblPuntos.setForeground(jugador.getColor());
        enTurno();

    }

    private void enTurno() {
        if (jugador.isTurno()) {

            lblAvatar.setIcon(new ImageIcon(jugador.getAvatar()));
            this.setBorder(BorderFactory.createLineBorder(jugador.getColor(), 2, true));
        } else {
            ImageIcon iconoOriginal = new ImageIcon(jugador.getAvatar());
            Image imgGris = GrayFilter.createDisabledImage(iconoOriginal.getImage());
            this.lblAvatar.setIcon(new ImageIcon(imgGris));
            this.setBorder(null);
        }
    }

    public JugadorPresentable getJugador() {
        return jugador;
    }

    public void setJugador(JugadorPresentable jugador) {
        this.jugador = jugador;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(451, 124));
        setMinimumSize(new java.awt.Dimension(451, 124));
        setSize(new java.awt.Dimension(451, 124));

        lblNombre.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblNombre.setText("NombreJugador");

        lblPuntos.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        lblPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntos.setText("0");

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setText("puntos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPuntos)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblNombre)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(lblAvatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntos;
    // End of variables declaration//GEN-END:variables


}
