package MVCJuegoEnCurso.vista;

import java.awt.Color;
import java.awt.Graphics;
import objetosPresentables.PuntoPresentable;

/**
 * representación gráfica de un punto del tablero.
 *
 * @author victoria
 */
public class PnlPunto extends javax.swing.JPanel {

    private PuntoPresentable punto;
    private PnlTablero tablero;
    private Color color;

    public PnlPunto(PuntoPresentable punto, PnlTablero tablero) {
        initComponents();
        this.punto = punto;
        this.tablero = tablero;
        setOpaque(false);
        setBorder(null);
        color = Color.BLACK;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(this.color);
        g.fillOval(getWidth() / 2 - 5, getHeight() / 2 - 5, 10, 10);
    }

    public PuntoPresentable getPunto() {
        return punto;
    }

    public void setColor(Color color) {
        this.color = color;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // Verificar si la interaccion esta habilitada (es turno del jugador)
        if (!tablero.isInteraccionHabilitada()) {
            return; // No es tu turno, ignorar click
        }

        this.setColor(Color.LIGHT_GRAY);
        repaint();
        tablero.agregarPuntoSeleccionado(punto);

    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
