package org.itson.presentacion;

import MVCJuegoEnCurso.observer.ObservadorMostrarMenu;
import java.awt.Color;

/**
 *
 * @author victoria
 */
public class FrmMenuInicio extends javax.swing.JFrame implements ObservadorMostrarMenu{

    private final Color COLOR_FONDO = new Color(224, 233, 255);

    public FrmMenuInicio() {
        initComponents();
        this.setBackground(COLOR_FONDO);
        this.setLocationRelativeTo(null);
        setSize(1050, 740);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnNuevaPartida = new javax.swing.JButton();
        btnUnirsePartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(224, 233, 255));

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titulo.png"))); // NOI18N

        btnNuevaPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/crearNuevaPartida.png"))); // NOI18N
        btnNuevaPartida.setBorder(null);
        btnNuevaPartida.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/crearNuevaPartidaHover.png"))); // NOI18N
        btnNuevaPartida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/crearNuevaPartidaHover.png"))); // NOI18N

        btnUnirsePartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/unirsePartida.png"))); // NOI18N
        btnUnirsePartida.setBorder(null);
        btnUnirsePartida.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/unirsePartidaHover.png"))); // NOI18N
        btnUnirsePartida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/unirsePartidaHover.png"))); // NOI18N

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/salir.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/salirHover.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/salirHover.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnirsePartida)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(351, 351, 351))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblTitulo)
                .addGap(165, 165, 165)
                .addComponent(btnNuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnUnirsePartida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnSalir)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUnirsePartida;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMenu() {
        this.setVisible(true);
    }
}
