/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.presentacion;

import MVCJuegoEnCurso.controlador.ControladorPartida;
import MVCJuegoEnCurso.observer.ObservableMostrarMenu;
import MVCJuegoEnCurso.observer.ObservadorCierrePantalla;
import MVCJuegoEnCurso.observer.ObservadorCierrePantallaGanada;
import MVCJuegoEnCurso.observer.ObservadorFinPartida;
import MVCJuegoEnCurso.observer.ObservadorMostrarMenu;
import java.awt.Color;
import objetosPresentables.JugadorPresentable;

/**
 *
 * @author pablo
 */
public class FrmPartidaGanada extends javax.swing.JFrame implements ObservadorFinPartida, ObservadorCierrePantallaGanada{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPartidaGanada.class.getName());

    private ControladorPartida controlador;
    private ObservadorMostrarMenu mostrarMenu;
    private JugadorPresentable jugador;
    
    /**
     * Creates new form FrmPartidaGanada
     * @param controlador
     */
    public FrmPartidaGanada(ControladorPartida controlador) {
        initComponents();
        getContentPane().setBackground(Color.decode("#D6F4D6"));
        this.controlador = controlador;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                controlador.mostrarMenu();
            }
        });
    }

    @Override
    public void partidaFinalizada(JugadorPresentable jugador) {
        this.jugador = jugador;
        this.nombre.setText(jugador.getNombre());
        this.score.setText(String.valueOf(jugador.getScore()));
        this.setVisible(true);
    }
    
    public void agregarObservadorMostrarMenu(ObservadorMostrarMenu ob){
        this.mostrarMenu = ob;
    }
    
    @Override
    public void cerrarPantalla() {
        this.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGanaste = new javax.swing.JLabel();
        lbNombre2 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        lbScore = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGanaste.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        txtGanaste.setText("Partida finalizada");

        lbNombre2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lbNombre2.setText("Ganador:");

        nombre.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        nombre.setText("nombre");

        lbScore.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lbScore.setText("Score:");

        score.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        score.setText("score");

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setText("Aceptar");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(393, 393, 393)
                                .addComponent(lbNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(441, 441, 441)
                                .addComponent(lbScore, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(txtGanaste, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 153, Short.MAX_VALUE)
                .addComponent(txtGanaste, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre2)
                    .addComponent(nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbScore)
                    .addComponent(score))
                .addGap(220, 220, 220)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        controlador.cerrarPantallaGanada();
        controlador.mostrarMenu();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FrmPartidaGanada().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lbNombre2;
    private javax.swing.JLabel lbScore;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel score;
    private javax.swing.JLabel txtGanaste;
    // End of variables declaration//GEN-END:variables



}
