package MVCConfiguracion.vista;

import MVCConfiguracion.controlador.ControladorArranque;
import MVCConfiguracion.modelo.IModeloArranqueLectura;
import MVCConfiguracion.observer.ObservadorSolicitudes;
import objetosPresentables.JugadorConfig;

/**
 *
 * @author victoria
 */
public class DlgInicioJuego extends javax.swing.JFrame implements ObservadorSolicitudes{
    
    private JugadorConfig jugador;
    private ControladorArranque controlador;
    private IModeloArranqueLectura modelo;
    
    
    public DlgInicioJuego(ControladorArranque controlador, IModeloArranqueLectura modelo) {
        initComponents();
        this.modelo = modelo;
        this.jugador = modelo.getSesion();
        this.controlador = controlador;
        setSize(695, 300);
        setLocationRelativeTo(null);
        setTitle("Solicitud de incio - Sesión de " + jugador.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJugador = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        btnMasTiempo = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(224, 233, 255));

        jPanel1.setBackground(new java.awt.Color(229, 227, 255));

        lblJugador.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        lblJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblJugador1.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        lblJugador1.setText("Se solicitó iniciar el juego");

        btnMasTiempo.setBackground(new java.awt.Color(229, 227, 255));
        btnMasTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/masTiempo.png"))); // NOI18N
        btnMasTiempo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMasTiempo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/masTiempoHover.png"))); // NOI18N
        btnMasTiempo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/masTiempoHover.png"))); // NOI18N
        btnMasTiempo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/masTiempoHover.png"))); // NOI18N
        btnMasTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasTiempoActionPerformed(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(229, 227, 255));
        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/iniciarJuego.png"))); // NOI18N
        btnIniciar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnIniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/iniciarJuegoHover.png"))); // NOI18N
        btnIniciar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/iniciarJuegoHover.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnMasTiempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIniciar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(lblJugador1)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblJugador)
                .addGap(27, 27, 27)
                .addComponent(lblJugador1)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMasTiempo)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasTiempoActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnMasTiempo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblJugador1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrar() {
        this.setVisible(true);
    }
}
