package MVCConfiguracion.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import objetosPresentables.JugadorConfig;

/**
 *
 * @author victoria
 */
public class PnlJugador extends javax.swing.JPanel {

    private JugadorConfig jugador;

    public PnlJugador(JugadorConfig jugador) {
        this.jugador = jugador;
        initComponents();
        cargarDatos();
    }

    private void cargarDatos() {
        this.lblNombre.setText(jugador.getNombre());
        this.lblNombre.setForeground(jugador.getColor());
        this.color.setBackground(jugador.getColor());
        Image avatar = jugador.getAvatar();
        this.lblAvatar.setIcon(new ImageIcon(avatar));

        if (jugador.isListo()) {
            this.lblStatus.setText("Listo");
            this.lblStatus.setForeground(Color.GREEN);
        } else {
            this.lblStatus.setText("Esperando");
            this.lblStatus.setForeground(Color.GRAY);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        color = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(224, 233, 255));

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatares/tiburonBallena.png"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblNombre.setText("NombreJugador");

        color.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout colorLayout = new javax.swing.GroupLayout(color);
        color.setLayout(colorLayout);
        colorLayout.setHorizontalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorLayout.setVerticalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        lblStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(51, 204, 0));
        lblStatus.setText("Listo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblStatus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAvatar)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblStatus)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel color;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
