/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MVCConfiguracion.vista.unirsePartida;

import javax.swing.Timer;

/**
 * Diálogo genérico para mostrar mensajes de rechazo de solicitud.
 * Se cierra automáticamente después de 3 segundos.
 *
 * @author Jack Murrieta
 */
public class DlgMostrarMensaje extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgMostrarMensaje.class.getName());
    private static final int AUTO_CLOSE_DELAY = 3000; // 3 segundos en milisegundos
    private Timer autoCloseTimer;

    /**
     * Creates new form DlgPartidaEnCurso con mensaje por defecto
     */
    public DlgMostrarMensaje(java.awt.Frame parent, boolean modal) {
        this(parent, modal, "<html><div style='text-align: center;'>La partida ya esta en curso.<br>Espere hasta que esta termine para iniciar una nueva partida o unirse a una.</div></html>");
    }

    /**
     * Creates new form DlgPartidaEnCurso con mensaje personalizado
     *
     * @param parent Frame padre
     * @param modal Si es modal
     * @param mensaje Mensaje HTML a mostrar
     */
    public DlgMostrarMensaje(java.awt.Frame parent, boolean modal, String mensaje) {
        super(parent, modal);

        initComponents();
        setSize(750, 480);
        setMensaje(mensaje);
        iniciarTemporizadorAutoCierre();
    }

    /**
     * Inicia un temporizador que cerrará automáticamente el diálogo después de 3 segundos.
     */
    private void iniciarTemporizadorAutoCierre() {
        autoCloseTimer = new Timer(AUTO_CLOSE_DELAY, e -> {
            System.out.println("[DlgMostrarMensaje] Auto-cierre después de 3 segundos");
            dispose();
        });
        autoCloseTimer.setRepeats(false); // Solo ejecutar una vez
        autoCloseTimer.start();
    }

    /**
     * Sobrescribe dispose para detener el timer si existe.
     */
    @Override
    public void dispose() {
        if (autoCloseTimer != null && autoCloseTimer.isRunning()) {
            autoCloseTimer.stop();
        }
        super.dispose();
    }

    /**
     * Establece el mensaje a mostrar en el diálogo.
     *
     * @param mensaje Mensaje HTML a mostrar
     */
    public void setMensaje(String mensaje) {
        jLabel1.setText(mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(221, 238, 255));

        jPanel1.setBackground(new java.awt.Color(221, 238, 255));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 20));

        jLabel1.setBackground(new java.awt.Color(221, 238, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 77, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><div style='text-align: center;'>La partida ya esta en curso.<br>Espere hasta que esta termine para iniciar una nueva partida o unirse a una.</div></html>");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(221, 238, 255));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/aceptar.png"))); // NOI18N
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/aceptarHover.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgMostrarMensaje dialog = new DlgMostrarMensaje(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
