/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FrmsUnirsePartida;

import MVCConfiguracion.controlador.ControladorUnisePartida;
import MVCConfiguracion.observer.INotificadorUnirsePartida;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class DlgUnirsePartida extends javax.swing.JDialog implements INotificadorUnirsePartida {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgUnirsePartida.class.getName());
    private ControladorUnisePartida controlador;

    /**
     * Creates new form DlgUnirsePartida
     */
    public DlgUnirsePartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(750, 480);
        configurarEventos();
    }

    public void setControlador(ControladorUnisePartida controlador) {
        this.controlador = controlador;
    }

    private void configurarEventos() {
        // Botón Solicitar Unirse - pide IP y puerto, luego envía solicitud
        btnSolicitarUnirse.addActionListener(e -> {
            if (controlador != null) {
                // Solicitar IP al usuario
                String ip = JOptionPane.showInputDialog(this,
                    "Ingrese la IP del host:",
                    "Conectar a partida",
                    JOptionPane.QUESTION_MESSAGE);

                if (ip != null && !ip.trim().isEmpty()) {
                    // Solicitar puerto al usuario
                    String puertoStr = JOptionPane.showInputDialog(this,
                        "Ingrese el puerto del host:",
                        "Conectar a partida",
                        JOptionPane.QUESTION_MESSAGE);

                    if (puertoStr != null && !puertoStr.trim().isEmpty()) {
                        try {
                            int puerto = Integer.parseInt(puertoStr);
                            controlador.enviarSolicitud(ip, puerto);
                            dispose(); // Cerrar después de enviar
                        } catch (NumberFormatException ex) {
                            JOptionPane.showMessageDialog(this,
                                "Puerto inválido. Debe ser un número.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        });

        // Botón Volver - cierra el diálogo
        btnVolver.addActionListener(e -> {
            dispose();
        });
    }

    @Override
    public void actualizar() {
        // Este método se puede usar para actualizar el estado del diálogo
        // Por ejemplo, cuando hay una partida disponible
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnSolicitarUnirse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(221, 238, 255));

        jPanel1.setBackground(new java.awt.Color(221, 238, 255));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 20));

        jPanel2.setBackground(new java.awt.Color(221, 238, 255));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/volver.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setFocusPainted(false);
        btnVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/volverHover.png"))); // NOI18N

        btnSolicitarUnirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/solicitarUnirse.png"))); // NOI18N
        btnSolicitarUnirse.setBorderPainted(false);
        btnSolicitarUnirse.setContentAreaFilled(false);
        btnSolicitarUnirse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSolicitarUnirse.setRolloverEnabled(true);
        btnSolicitarUnirse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/solicitarUnirseHover.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnSolicitarUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSolicitarUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jLabel1.setBackground(new java.awt.Color(221, 238, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 77, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><div style='text-align: center;'>Se encontró una partida existente.<br>¿Deseas unirte?</div></html>");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgUnirsePartida dialog = new DlgUnirsePartida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitarUnirse;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
